name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4


    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: 'Build and push image'
      run: |
        docker build . -t ${{ secrets.ACR_NAME }}.azurecr.io/hello-world:${{ github.sha }}
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/hello-world:${{ github.sha }}

    - name: 'Update deployment file'
      run: |
        sed -i 's/__ACR_NAME__/${{ secrets.ACR_NAME }}/g' k8s/deployment.yaml
        sed -i "s|image: .*/hello-world:.*|image: ${{ secrets.ACR_NAME }}.azurecr.io/hello-world:${{ github.sha }}|g" k8s/deployment.yaml

    - name: 'Commit and push updated deployment file'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add k8s/deployment.yaml
        if git diff-index --quiet HEAD; then
          echo "No changes to commit."
        else
          git commit -m "Update deployment image tag to ${{ github.sha }} [skip ci]"
          git push
        fi
