name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4


    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: 'Build and push image'
      run: |
        docker build . -t ${{ secrets.ACR_NAME }}.azurecr.io/hello-world:${{ github.sha }}
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/hello-world:${{ github.sha }}

    - name: 'Update deployment file'
      run: |
        sed -i 's/__ACR_NAME__/${{ secrets.ACR_NAME }}/g' k8s/deployment.yaml
        sed -i 's/__IMAGE_TAG__/${{ github.sha }}/g' k8s/deployment.yaml

    - name: 'Upload artifact'
      uses: actions/upload-artifact@v4
      with:
        name: k8s
        path: k8s
